<a href="https://colab.research.google.com/github/Viktory4121/MAPI/blob/main/PseudoInversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# Псевдообращение алгоритмом Фаддеева
#A = np.array([[-1,0,2,0,5,-2],[4,5,5,2,1,-1],[2,1,1,0,8,-1],[0,1,-3,-4,2,-3]])
#A = np.array([[7,0,4,9,6,0],[3,0,4,1,1,2],[0,1,1,2,6,7],[1,4,7,4,9,5]])
A = np.array([[-1,4,-2],[-1,4,-2],[1,26,-1]])
n = len(A[0])
A_T = A.transpose()
A_T_A = A_T.dot(A) #перемножены транспонированная матрица и обычная
F = np.diag(np.diag(np.ones([n,n]))) #единичная матрица
mu = sum(np.diag(A_T_A)) #это фи1 (сумма значений матрицы A_T_A по диагонали)
print("A = \n", A)
#print("A^T * A = \n", A_T_A)
print("phi_1 = ", mu)

A = 
 [[-1  4 -2]
 [-1  4 -2]
 [ 1 26 -1]]
phi_1 =  720


In [ ]:
print("det(A) = ", np.linalg.det(A))

det(A) =  0.0


In [8]:
def print_matrix(A):
  m = len(A)
  n = len(A[0])
  for row in A:
    for i in row:
      print("{:.6f}\t\t".format(i), end = "" )
    print()

In [ ]:
def pseudo(A_T_A, F, mu, A_T):
    n = len(F)
    I = np.diag(np.diag(np.ones([n,n])))
    i = 2
    while mu != 0:
        if sum(np.diag(A_T_A.dot(mu*I - A_T_A.dot(F))))/float(i) == 0:
            _mu = mu
            _F = F
        F = mu*I - A_T_A.dot(F)
        mu = sum(np.diag(A_T_A.dot(F)))/float(i)
        
        print("Шаг", i)
        print("F:\n")
        print_matrix(F)
        #print("\nA_T_A*F:\n", A_T_A.dot(F))
        print("phi\n", mu)
        print("\n\n")
        
        i+=1
    print("A*: 1/", _mu, "\n")
    A_psevv = _F.dot(A_T)
    print_matrix(A_psevv)
    return(A_psevv/_mu, _mu)

A_psev, muu = pseudo(A_T_A, F, mu, A_T)

Шаг 2
F:

717.000000		-18.000000		-3.000000		
-18.000000		12.000000		42.000000		
-3.000000		42.000000		711.000000		
phi
 6426.0



Шаг 3
F:

4608.000000		-288.000000		-2880.000000		
-288.000000		18.000000		180.000000		
-2880.000000		180.000000		1800.000000		
phi
 0.0



A*: 1/ 6426.0 

-783.000000		-783.000000		252.000000		
-18.000000		-18.000000		252.000000		
-1251.000000		-1251.000000		378.000000		


In [ ]:
print_matrix(A_psev) #без вынесения общего знаменателя за скобку

-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		


In [ ]:
#Проверка 1 ((A A^+)^T = A A^+)
Check1_1 = (A.dot(A_psev)).transpose()
Check1_2 = A.dot(A_psev)
print_matrix(Check1_1)
print()
print_matrix(Check1_2)

0.500000		0.500000		0.000000		
0.500000		0.500000		0.000000		
0.000000		0.000000		1.000000		

0.500000		0.500000		0.000000		
0.500000		0.500000		0.000000		
0.000000		0.000000		1.000000		


In [ ]:
#Проверка 2 ((A^+ A)^T = A^+ A)
#A_psev1 = A_psev.dot(muu)
Check2_1 = (A_psev.dot(A)).transpose()
Check2_2 = A_psev.dot(A)
print_matrix(Check2_1)
print()
print_matrix(Check2_2)

0.282913		0.044818		0.448179		
0.044818		0.997199		-0.028011		
0.448179		-0.028011		0.719888		

0.282913		0.044818		0.448179		
0.044818		0.997199		-0.028011		
0.448179		-0.028011		0.719888		


In [ ]:
#Проверка 3 (A A^+ A = A)
Check3_1 = A.dot(A_psev).dot(A)
Check3_2 = A
print(Check3_1)
print(Check3_2)

[[-1.  4. -2.]
 [-1.  4. -2.]
 [ 1. 26. -1.]]
[[-1  4 -2]
 [-1  4 -2]
 [ 1 26 -1]]


In [ ]:
#Проверка 4 (A^+ A A^+ = A^+)
Check4_1 = A_psev.dot(A).dot(A_psev)
Check4_2 = A_psev
print_matrix(Check4_1)
print()
print_matrix(Check4_2)

-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		

-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		


## Алгоритм Гревиля


In [2]:
import numpy as np

In [3]:
A = np.array([[7,0,4,9,6,0],[3,0,4,1,1,2],[0,1,1,2,6,7],[1,4,7,4,9,5]])

#a1 = A[:,0:1]
#a2 = A[:,1:2]
#a3 = A[:,2:3]
#a4 = A[:,3:4]
#a5 = A[:,4:5]
#a6 = A[:,5:6]

#A1 = A[:,0:1]
#A2 = A[:,0:2]
#A3 = A[:,0:3]
#A4 = A[:,0:4]
#A5 = A[:,0:5]
#A6 = A.copy()

In [4]:
def norm(A): #норма вектора
  return ((A.T).dot(A))

In [5]:
#Шаг 1
T1 = A[:,0:1].transpose()
if(A[:,0:1].any()):
  t1 = norm(A[:,0:1])
else:
  t1 = 0
print(T1)
print(t1)

[[7 3 0 1]]
[[59]]


In [10]:
#ti - число
#Ti - A_i^+
#Fi - вектор
def Greville(A, T1, t1):
  i = 1
  n = len(A[0])
  I = np.diag(np.diag(np.ones([n,n])))

  t = t1.copy()
  T = T1.copy()
  F = np.zeros((n,n))

  while(i < n):
    #ci = (t[i-1]*I - A[i-1]*T[i-1])a[i] - раскрыть скобки:
    c = t1*A[:,i:i+1] - (A[:,0:i].dot(T1)).dot(A[:,i:i+1])
    #d = 1 + norm(T1.dot(A[:,i:i+1]))

    if (c.any()): #если вектор не нулевой
      F = c.T
      #ti = t[i-1]*norm(a2) - a[i]^T * A[i-1] * T[i-1] * a[i]
      t = t1*norm(A[:,i:i+1]) - (((A[:,i:i+1].T).dot(A[:,0:i])).dot(T1)).dot(A[:,i:i+1])
    else: #если нулевой
      F = ((A[:,i:i+1].T).dot(T1.T)).dot(T1)
      t = t1**2 + norm(T1.dot(A[:,i:i+1]))
    
    f = 1/t1 * (T1*t - (T1.dot(A[:,i:i+1])).dot(F))
    T = np.vstack((f, F))

    print("Шаг ", i+1, ":")
    print("F:\n", F)
    print("t =", t)
    print("T:\n")
    print_matrix(T)
    print()
    T1 = T
    t1 = t
    i += 1
  return (T, t)

T, t = Greville(A, T1, t1)

Шаг  2 :
F:
 [[-28 -12  59 232]]
t = [[987]]
T:

119.000000		51.000000		-4.000000		1.000000		
-28.000000		-12.000000		59.000000		232.000000		

Шаг  3 :
F:
 [[-833. 1899. -536.  134.]]
t = [[4666.]]
T:

1139.000000		-1073.000000		352.000000		-88.000000		
1153.000000		-2987.000000		1106.000000		890.000000		
-833.000000		1899.000000		-536.000000		134.000000		

Шаг  4 :
F:
 [[-180.  612. 2304. -576.]]
t = [[1296.]]
T:

684.000000		-1548.000000		-4608.000000		1152.000000		
828.000000		-2556.000000		-6192.000000		1872.000000		
-468.000000		1332.000000		2880.000000		-720.000000		
-180.000000		612.000000		2304.000000		-576.000000		

Шаг  5 :
F:
 [[-3.07203840e+07  8.59455360e+07  2.24316864e+08 -6.18762240e+07]]
t = [[6.92318016e+08]]
T:

16372368.000000		149501376.000000		86913648.000000		-87588864.000000		
18202320.000000		-178879104.000000		-210922704.000000		145779264.000000		
-28987632.000000		93218688.000000		-75350736.000000		60543936.000000		
97553808.000000		-215006400.000000		-183654

In [13]:
print("A^+ = ")
print_matrix(T/t)

A^+ = 
0.045456		0.136151		0.025446		-0.078629		
-0.025052		-0.070509		-0.068993		0.097820		
-0.043649		0.141157		-0.100673		0.083545		
0.080370		-0.089048		0.012597		-0.013820		
0.022179		-0.119375		0.018532		0.056768		
-0.032159		0.117671		0.147611		-0.070619		
