<a href="https://colab.research.google.com/github/Viktory4121/MAPI/blob/main/PseudoInversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

In [84]:
# Псевдообращение алгоритмом Фаддеева
#A = np.array([[-1,0,2,0,5,-2],[4,5,5,2,1,-1],[2,1,1,0,8,-1],[0,1,-3,-4,2,-3]])
#A = np.array([[7,0,4,9,6,0],[3,0,4,1,1,2],[0,1,1,2,6,7],[1,4,7,4,9,5]])
A = np.array([[-1,4,-2],[-1,4,-2],[1,26,-1]])
n = len(A[0])
A_T = A.transpose()
A_T_A = A_T.dot(A) #перемножены транспонированная матрица и обычная
F = np.diag(np.diag(np.ones([n,n]))) #единичная матрица
mu = sum(np.diag(A_T_A)) #это фи1 (сумма значений матрицы A_T_A по диагонали)
print("A = \n", A)
#print("A^T * A = \n", A_T_A)
print("phi_1 = ", mu)

A = 
 [[-1  4 -2]
 [-1  4 -2]
 [ 1 26 -1]]
phi_1 =  720


In [85]:
print("det(A) = ", np.linalg.det(A))

det(A) =  0.0


In [86]:
def print_matrix(A):
  m = len(A)
  n = len(A[0])
  for row in A:
    for i in row:
      print("{:.6f}\t\t".format(i), end = "" )
    print()

In [88]:
def pseudo(A_T_A, F, mu, A_T):
    n = len(F)
    I = np.diag(np.diag(np.ones([n,n])))
    i = 2
    while mu != 0:
        if sum(np.diag(A_T_A.dot(mu*I - A_T_A.dot(F))))/float(i) == 0:
            _mu = mu
            _F = F
        F = mu*I - A_T_A.dot(F)
        mu = sum(np.diag(A_T_A.dot(F)))/float(i)
        
        print("Шаг", i)
        print("F:\n")
        print_matrix(F)
        #print("\nA_T_A*F:\n", A_T_A.dot(F))
        print("phi\n", mu)
        print("\n\n")
        
        i+=1
    print("A*: 1/", _mu, "\n")
    A_psevv = _F.dot(A_T)
    print_matrix(A_psevv)
    return(A_psevv/_mu, _mu)

A_psev, muu = pseudo(A_T_A, F, mu, A_T)

Шаг 2
F:

717.000000		-18.000000		-3.000000		
-18.000000		12.000000		42.000000		
-3.000000		42.000000		711.000000		
phi
 6426.0



Шаг 3
F:

4608.000000		-288.000000		-2880.000000		
-288.000000		18.000000		180.000000		
-2880.000000		180.000000		1800.000000		
phi
 0.0



A*: 1/ 6426.0 

-783.000000		-783.000000		252.000000		
-18.000000		-18.000000		252.000000		
-1251.000000		-1251.000000		378.000000		


In [89]:
print_matrix(A_psev) #без вынесения общего знаменателя за скобку

-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		


In [90]:
#Проверка 1 ((A A^+)^T = A A^+)
Check1_1 = (A.dot(A_psev)).transpose()
Check1_2 = A.dot(A_psev)
print_matrix(Check1_1)
print()
print_matrix(Check1_2)

0.500000		0.500000		0.000000		
0.500000		0.500000		0.000000		
0.000000		0.000000		1.000000		

0.500000		0.500000		0.000000		
0.500000		0.500000		0.000000		
0.000000		0.000000		1.000000		


In [91]:
#Проверка 2 ((A^+ A)^T = A^+ A)
#A_psev1 = A_psev.dot(muu)
Check2_1 = (A_psev.dot(A)).transpose()
Check2_2 = A_psev.dot(A)
print_matrix(Check2_1)
print()
print_matrix(Check2_2)

0.282913		0.044818		0.448179		
0.044818		0.997199		-0.028011		
0.448179		-0.028011		0.719888		

0.282913		0.044818		0.448179		
0.044818		0.997199		-0.028011		
0.448179		-0.028011		0.719888		


In [92]:
#Проверка 3 (A A^+ A = A)
Check3_1 = A.dot(A_psev).dot(A)
Check3_2 = A
print(Check3_1)
print(Check3_2)

[[-1.  4. -2.]
 [-1.  4. -2.]
 [ 1. 26. -1.]]
[[-1  4 -2]
 [-1  4 -2]
 [ 1 26 -1]]


In [93]:
#Проверка 4 (A^+ A A^+ = A^+)
Check4_1 = A_psev.dot(A).dot(A_psev)
Check4_2 = A_psev
print_matrix(Check4_1)
print()
print_matrix(Check4_2)

-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		

-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		


## Алгоритм Гревиля


In [103]:
import numpy as np
import sympy

In [134]:
A = np.array([[7,0,4,9,6,0],[3,0,4,1,1,2],[0,1,1,2,6,7],[1,4,7,4,9,5]])

a1 = A[:,0:1]
a2 = A[:,1:2]
a3 = A[:,2:3]
a4 = A[:,3:4]
a5 = A[:,4:5]
a6 = A[:,5:6]

A1 = A[:,0:1]
A2 = A[:,0:2]
A3 = A[:,0:3]
A4 = A[:,0:4]
A5 = A[:,0:5]
A6 = A.copy()

In [129]:
#Шаг 1
T1 = a1.transpose()
t1 = a1.transpose().dot(a1)
print(T1)
print(t1)

[[7 3 0 1]]
[[59]]


In [135]:
def Greville(A, T1, t1):
  i = 2
  n = len(A[0])
  I = np.diag(np.diag(np.ones([n,n])))

  while(i <= n):
    c = (I - A[:,0:i].dot(T1)).dot(A[:,i:i+1])
    if (c == 0):
      F = A[:,i].transpose().dot(T1.transpose()).dot(T1)
      t = t1**2 + (T1.dot(A[:,i]))**2
    else:
      F = c.transpose()
      t = t1.dot(A[:,i:i+1].transpose().dot(A[:,i:i+1])) - A[:,i:i+1].transpose().dot(A[:,0:i]).dot(T1).dot(A[:,i:i+1])
    
    T = T1

    print("Шаг ", i)
    print("F:\n", F)
    print("t=", t)
    print("T:\n", T)
    break
    T1 = T
    t1 = t
    i +=1

In [136]:
Greville(A, T1, t1)

ValueError: ignored