<a href="https://colab.research.google.com/github/Viktory4121/MAPI/blob/main/PseudoInversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import numpy as np

In [91]:
# Псевдообращение алгоритмом Фаддеева
#A = np.array([[-1,0,2,0,5,-2],[4,5,5,2,1,-1],[2,1,1,0,8,-1],[0,1,-3,-4,2,-3]])
#A = np.array([[7,0,4,9,6,0],[3,0,4,1,1,2],[0,1,1,2,6,7],[1,4,7,4,9,5]])
A = np.array([[12,7,9,36],[98,3,5,2],[6,78,3,1],[1,3,10,41]])
A_T = A.transpose()
A_T_A = A_T.dot(A) #перемножены транспонированная матрица и обычная
F = np.diag(np.diag(np.ones([4,4]))) #единичная матрица
mu = sum(np.diag(A_T_A)) #это фи1 (сумма значений матрицы A_T_A по диагонали)
print("A = \n", A)
print("A^T * A = \n", A_T_A)
print("mu = ", mu)

A = 
 [[12  7  9 36]
 [98  3  5  2]
 [ 6 78  3  1]
 [ 1  3 10 41]]
A^T * A = 
 [[9785  849  626  675]
 [ 849 6151  342  459]
 [ 626  342  215  747]
 [ 675  459  747 2982]]
mu =  19133


In [92]:
print("det(A) = ", np.linalg.det(A))

det(A) =  -131705.99999999988


In [115]:
def print_matrix(A):
  m = len(A)
  n = len(A[0])
  for row in A:
    for i in row:
      print("{:.6f}\t\t".format(i), end = "" )
    print()

In [116]:
def pseudo(A_T_A, F, mu, A_T):
    I = np.diag(np.diag(np.ones([4,4])))
    i = 2
    while mu != 0:
        if sum(np.diag(A_T_A.dot(mu*I - A_T_A.dot(F))))/float(i) == 0:
            _mu = mu
            _F = F
        F = mu*I - A_T_A.dot(F)
        mu = sum(np.diag(A_T_A.dot(F)))/float(i)
        
        print("Шаг", i)
        print("F:\n")
        print_matrix(F)
        #print("\nA_T_A*F:\n", A_T_A.dot(F))
        print("mu\n", mu)
        print("\n\n")
        
        i+=1
    print("A*: 1/", _mu, "\n")
    A_psevv = _F.dot(A_T)
    print_matrix(A_psevv)
    return(A_psevv/_mu, _mu)

A_psev, muu = pseudo(A_T_A, F, mu, A_T)

Шаг 2
F:

9348.000000 	-849.000000 	-626.000000 	-675.000000 	
-849.000000 	12982.000000 	-342.000000 	-459.000000 	
-626.000000 	-342.000000 	18918.000000 	-747.000000 	
-675.000000 	-459.000000 	-747.000000 	16151.000000 	
mu
 109322101.0



Шаг 3
F:

19420223.000000 	-2190336.000000 	-4922675.000000 	-3439737.000000 	
-2190336.000000 	30518265.000000 	-3491967.000000 	-3761451.000000 	
-4922675.000000 	-3491967.000000 	106321580.000000 	-11324664.000000 	
-3439737.000000 	-3761451.000000 	-11324664.000000 	62384134.000000 	
mu
 183115589106.0



Шаг 4
F:

351719340.000000 	247381542.000000 	-7780106022.000000 	1831247658.000000 	
247381542.000000 	178095078.000000 	-5505519492.000000 	1295739396.000000 	
-7780106022.000000 	-5505519492.000000 	172991820678.000000 	-40726453734.000000 	
1831247658.000000 	1295739396.000000 	-40726453734.000000 	9593954010.000000 	
mu
 17346470436.0



Шаг 5
F:

0.000000 	0.000000 	0.000000 	0.000000 	
0.000000 	0.000000 	0.000000 	0.000000 	
0.000000

In [117]:
print_matrix(A_psev)

0.107011 	-0.001579 	-0.005937 	-0.093739 	
0.075646 	-0.009134 	0.008929 	-0.066193 	
-2.370849 	0.261681 	0.123244 	2.065950 	
0.570111 	-0.063118 	-0.030568 	-0.472370 	


In [118]:
#Проверка 1
Check1_1 = (A.dot(A_psev)).transpose()
Check1_2 = A.dot(A_psev)
print_matrix(Check1_1)
print()
print_matrix(Check1_2)

1.000000 	-0.000000 	-0.000000 	0.000000 	
0.000000 	1.000000 	0.000000 	-0.000000 	
0.000000 	0.000000 	1.000000 	0.000000 	
0.000000 	0.000000 	-0.000000 	1.000000 	

1.000000 	0.000000 	0.000000 	0.000000 	
-0.000000 	1.000000 	0.000000 	0.000000 	
-0.000000 	0.000000 	1.000000 	-0.000000 	
0.000000 	-0.000000 	0.000000 	1.000000 	


In [119]:
#Проверка 2
A_psev1 = A_psev.dot(muu)
Check2_1 = (A_psev1.dot(A)).transpose()
Check2_2 = A_psev1.dot(A)
print_matrix(Check2_1)
print_matrix(Check2_2)

17346470436.000000 	0.000000 	0.000000 	0.000000 	
0.000000 	17346470436.000000 	0.000000 	0.000000 	
0.000000 	0.000000 	17346470436.000000 	0.000000 	
0.000000 	0.000000 	0.000000 	17346470436.000000 	
17346470436.000000 	0.000000 	0.000000 	0.000000 	
0.000000 	17346470436.000000 	0.000000 	0.000000 	
0.000000 	0.000000 	17346470436.000000 	0.000000 	
0.000000 	0.000000 	0.000000 	17346470436.000000 	


In [120]:
#Проверка 3
Check3_1 = A.dot(A_psev).dot(A)
Check3_2 = A
print(Check3_1)
print(Check3_2)

[[12.  7.  9. 36.]
 [98.  3.  5.  2.]
 [ 6. 78.  3.  1.]
 [ 1.  3. 10. 41.]]
[[12  7  9 36]
 [98  3  5  2]
 [ 6 78  3  1]
 [ 1  3 10 41]]


In [121]:
#Проверка 4
Check4_1 = A_psev1.dot(A).dot(A_psev)
Check4_2 = A_psev1
print_matrix(Check4_1)
print()
print_matrix(Check4_2)

1856264364.000000 	-27394848.000000 	-102994092.000000 	-1626042276.000000 	
1312186878.000000 	-158442318.000000 	154886256.000000 	-1148212908.000000 	
-41125857030.000000 	4539247290.000000 	2137851792.000000 	35836939188.000000 	
9889408422.000000 	-1094871978.000000 	-530248356.000000 	-8193957084.000000 	

1856264364.000000 	-27394848.000000 	-102994092.000000 	-1626042276.000000 	
1312186878.000000 	-158442318.000000 	154886256.000000 	-1148212908.000000 	
-41125857030.000000 	4539247290.000000 	2137851792.000000 	35836939188.000000 	
9889408422.000000 	-1094871978.000000 	-530248356.000000 	-8193957084.000000 	


## Алгоритм Гревиля


In [ ]:
import numpy as np

In [ ]:
A = np.array([[7,0,4,9,6,0],[3,0,4,1,1,2],[0,1,1,2,6,7],[1,4,7,4,9,5]])
A1 = np.array([7,3,0,1]).transpose()
A2 = np.array([[7,0],[3,0],[0,1],[1,4]])
A3 = np.array([[7,0,4],[3,0,4],[0,1,1],[1,4,7]])
A4 = np.array([[7,0,4,9],[3,0,4,1],[0,1,1,2],[1,4,7,4]])
A5 = np.array([[7,0,4,9,6],[3,0,4,1,1],[0,1,1,2,6],[1,4,7,4,9]])
A6 = A

In [ ]:
a1 = np.array([7,3,0,1]).transpose()
a2 = np.array([0,0,1,4]).transpose()
a3 = np.array([4,4,1,7]).transpose()
a4 = np.array([9,1,2,4]).transpose()
a5 = np.array([6,1,6,9]).transpose()
a6 = np.array([0,2,7,5]).transpose()

In [ ]:
#Шаг 1
T1 = a1.transpose()
t1 = a1.transpose().dot(a1)
print(T1)
print(t1)


[7 3 0 1]
59


In [ ]:
def Greville(A, T1, t1):
  i = 2
  I = np.diag(np.diag(np.ones([4,4])))

  while(i <= A.shape[1]):
    c = (t1*I - A[:,0:i].dot(T1)).dot(A[:,i])
    if (c == 0):
      F = A[:,i].transpose().dot(T1.transpose()).dot(T1)
      t = t1**2 + (T1.dot(A[:,i]))**2
    else:
      F = c.transpose()
      t = t1.dot(A[:,i].transpose().dot(A[:,i])) - A[:,i].transpose().dot(A[:,0:i]).dot(T1).dot(A[:,i])
    
    T = T1

    print("Шаг ", i)
    print("F:\n", F)
    print("t=", t)
    print("T:\n", T)
    break
    T1 = T
    t1 = t
    i +=1

In [ ]:
Greville(A, T1, t1)

ValueError: ignored