<a href="https://colab.research.google.com/github/Viktory4121/MAPI/blob/main/PseudoInversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import random as r

In [56]:
# Псевдообращение алгоритмом Фаддеева
#A = np.array([[-1,0,2,0,5,-2],[4,5,5,2,1,-1],[2,1,1,0,8,-1],[0,1,-3,-4,2,-3]])
#A = np.array([[7,0,4,9,6,0],[3,0,4,1,1,2],[0,1,1,2,6,7],[1,4,7,4,9,5]])
A = np.array([[-1,4,-2],[-1,4,-2],[1,26,-1]])
n = len(A[0])
A_T = A.transpose()
A_T_A = A_T.dot(A) #перемножены транспонированная матрица и обычная
F = np.diag(np.diag(np.ones([n,n]))) #единичная матрица
mu = sum(np.diag(A_T_A)) #это фи1 (сумма значений матрицы A_T_A по диагонали)
print("A = \n", A)
print("A^T * A = \n", A_T_A)
print("mu = ", mu)

A = 
 [[-1  4 -2]
 [-1  4 -2]
 [ 1 26 -1]]
A^T * A = 
 [[  3  18   3]
 [ 18 708 -42]
 [  3 -42   9]]
mu =  720


In [57]:
print("det(A) = ", np.linalg.det(A))

det(A) =  0.0


In [58]:
def print_matrix(A):
  m = len(A)
  n = len(A[0])
  for row in A:
    for i in row:
      print("{:.6f}\t\t".format(i), end = "" )
    print()

In [59]:
def pseudo(A_T_A, F, mu, A_T):
    n = len(F)
    I = np.diag(np.diag(np.ones([n,n])))
    i = 2
    while mu != 0:
        if sum(np.diag(A_T_A.dot(mu*I - A_T_A.dot(F))))/float(i) == 0:
            _mu = mu
            _F = F
        F = mu*I - A_T_A.dot(F)
        mu = sum(np.diag(A_T_A.dot(F)))/float(i)
        
        print("Шаг", i)
        print("F:\n")
        print_matrix(F)
        #print("\nA_T_A*F:\n", A_T_A.dot(F))
        print("mu\n", mu)
        print("\n\n")
        
        i+=1
    print("A*: 1/", _mu, "\n")
    A_psevv = _F.dot(A_T)
    print_matrix(A_psevv)
    return(A_psevv/_mu, _mu)

A_psev, muu = pseudo(A_T_A, F, mu, A_T)

Шаг 2
F:

717.000000		-18.000000		-3.000000		
-18.000000		12.000000		42.000000		
-3.000000		42.000000		711.000000		
mu
 6426.0



Шаг 3
F:

4608.000000		-288.000000		-2880.000000		
-288.000000		18.000000		180.000000		
-2880.000000		180.000000		1800.000000		
mu
 0.0



A*: 1/ 6426.0 

-783.000000		-783.000000		252.000000		
-18.000000		-18.000000		252.000000		
-1251.000000		-1251.000000		378.000000		


In [54]:
print_matrix(A_psev)

-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		


In [55]:
#Проверка 1
Check1_1 = (A.dot(A_psev)).transpose()
Check1_2 = A.dot(A_psev)
print_matrix(Check1_1)
print()
print_matrix(Check1_2)

0.500000		0.500000		0.000000		
0.500000		0.500000		0.000000		
0.000000		0.000000		1.000000		

0.500000		0.500000		0.000000		
0.500000		0.500000		0.000000		
0.000000		0.000000		1.000000		


In [51]:
#Проверка 2
#A_psev1 = A_psev.dot(muu)
Check2_1 = (A_psev.dot(A)).transpose()
Check2_2 = A_psev.dot(A)
print_matrix(Check2_1)
print()
print_matrix(Check2_2)

0.282913		0.044818		0.448179		
0.044818		0.997199		-0.028011		
0.448179		-0.028011		0.719888		

0.282913		0.044818		0.448179		
0.044818		0.997199		-0.028011		
0.448179		-0.028011		0.719888		


In [52]:
#Проверка 3
Check3_1 = A.dot(A_psev).dot(A)
Check3_2 = A
print(Check3_1)
print(Check3_2)

[[-1.  4. -2.]
 [-1.  4. -2.]
 [ 1. 26. -1.]]
[[-1  4 -2]
 [-1  4 -2]
 [ 1 26 -1]]


In [53]:
#Проверка 4
Check4_1 = A_psev.dot(A).dot(A_psev)
Check4_2 = A_psev
print_matrix(Check4_1)
print()
print_matrix(Check4_2)

-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		

-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		


## Алгоритм Гревиля


In [ ]:
import numpy as np

In [ ]:
A = np.array([[7,0,4,9,6,0],[3,0,4,1,1,2],[0,1,1,2,6,7],[1,4,7,4,9,5]])
A1 = np.array([7,3,0,1]).transpose()
A2 = np.array([[7,0],[3,0],[0,1],[1,4]])
A3 = np.array([[7,0,4],[3,0,4],[0,1,1],[1,4,7]])
A4 = np.array([[7,0,4,9],[3,0,4,1],[0,1,1,2],[1,4,7,4]])
A5 = np.array([[7,0,4,9,6],[3,0,4,1,1],[0,1,1,2,6],[1,4,7,4,9]])
A6 = A

In [ ]:
a1 = np.array([7,3,0,1]).transpose()
a2 = np.array([0,0,1,4]).transpose()
a3 = np.array([4,4,1,7]).transpose()
a4 = np.array([9,1,2,4]).transpose()
a5 = np.array([6,1,6,9]).transpose()
a6 = np.array([0,2,7,5]).transpose()

In [ ]:
#Шаг 1
T1 = a1.transpose()
t1 = a1.transpose().dot(a1)
print(T1)
print(t1)


[7 3 0 1]
59


In [ ]:
def Greville(A, T1, t1):
  i = 2
  I = np.diag(np.diag(np.ones([4,4])))

  while(i <= A.shape[1]):
    c = (t1*I - A[:,0:i].dot(T1)).dot(A[:,i])
    if (c == 0):
      F = A[:,i].transpose().dot(T1.transpose()).dot(T1)
      t = t1**2 + (T1.dot(A[:,i]))**2
    else:
      F = c.transpose()
      t = t1.dot(A[:,i].transpose().dot(A[:,i])) - A[:,i].transpose().dot(A[:,0:i]).dot(T1).dot(A[:,i])
    
    T = T1

    print("Шаг ", i)
    print("F:\n", F)
    print("t=", t)
    print("T:\n", T)
    break
    T1 = T
    t1 = t
    i +=1

In [ ]:
Greville(A, T1, t1)

ValueError: ignored