<a href="https://colab.research.google.com/github/Viktory4121/MAPI/blob/main/PseudoInversion_Faddeev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Алгоритм Фаддеева

In [13]:
import numpy as np
A = np.array([[-1,4,-2],[-1,4,-2],[1,26,-1]])
n = len(A[0])
A_T = A.transpose()
A_T_A = A_T.dot(A) #перемножены транспонированная матрица и обычная
F = np.diag(np.diag(np.ones([n,n]))) #единичная матрица
mu = sum(np.diag(A_T_A)) #это фи1 (сумма значений матрицы A_T_A по диагонали)
print("Шаг 1")
print("A = \n", A)
print("phi_1 = ", mu)
print("det(A) = ", np.linalg.det(A))

def print_matrix(A):
  m = len(A)
  n = len(A[0])
  for row in A:
    for i in row:
      print("{:.6f}\t\t".format(i), end = "" )
    print()

def pseudo(A_T_A, F, mu, A_T):
    n = len(F)
    I = np.diag(np.diag(np.ones([n,n])))
    i = 2
    while mu != 0:
        if sum(np.diag(A_T_A.dot(mu*I - A_T_A.dot(F))))/float(i) == 0:
            _mu = mu
            _F = F
        F = mu*I - A_T_A.dot(F)
        mu = sum(np.diag(A_T_A.dot(F)))/float(i)
        
        print("\nШаг", i)
        print("F:")
        print_matrix(F)
        #print("\nA_T_A*F:\n", A_T_A.dot(F))
        print("phi\n", mu)
        
        i+=1

    print("\n\nРЕЗУЛЬТАТ:\nA*: 1/", _mu)
    A_psevv = _F.dot(A_T)
    print_matrix(A_psevv)

    print("\nили A*:")
    print_matrix(A_psevv/_mu)
    return(A_psevv/_mu, _mu)

A_psev, muu = pseudo(A_T_A, F, mu, A_T)

Шаг 1
A = 
 [[-1  4 -2]
 [-1  4 -2]
 [ 1 26 -1]]
phi_1 =  720
det(A) =  0.0

Шаг 2
F:
717.000000		-18.000000		-3.000000		
-18.000000		12.000000		42.000000		
-3.000000		42.000000		711.000000		
phi
 6426.0

Шаг 3
F:
4608.000000		-288.000000		-2880.000000		
-288.000000		18.000000		180.000000		
-2880.000000		180.000000		1800.000000		
phi
 0.0


РЕЗУЛЬТАТ:
A*: 1/ 6426.0
-783.000000		-783.000000		252.000000		
-18.000000		-18.000000		252.000000		
-1251.000000		-1251.000000		378.000000		

или A*:
-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		


#Проверки Мура-Пенроуза

In [18]:
#Проверка 1 ((A A^+)^T = A A^+)
print("Проверка 1.")
Check1_1 = (A.dot(A_psev)).transpose()
Check1_2 = A.dot(A_psev)
print("(A A^+)^T:")
print_matrix(Check1_1)
print()
print("A A^+:")
print_matrix(Check1_2)

#Проверка 2 ((A^+ A)^T = A^+ A)
#A_psev1 = A_psev.dot(muu)
print("\n\nПроверка 2.")
Check2_1 = (A_psev.dot(A)).transpose()
Check2_2 = A_psev.dot(A)
print("(A^+ A)^T:")
print_matrix(Check2_1)
print()
print("A^+ A:")
print_matrix(Check2_2)

#Проверка 3 (A A^+ A = A)
print("\n\nПроверка 3.")
Check3_1 = A.dot(A_psev).dot(A)
Check3_2 = A
print("A A^+ A:")
print_matrix(Check3_1)
print("A:")
print_matrix(Check3_2)

#Проверка 4 (A^+ A A^+ = A^+)
print("\n\nПроверка 4.")
Check4_1 = A_psev.dot(A).dot(A_psev)
Check4_2 = A_psev
print("A^+ A A^+:")
print_matrix(Check4_1)
print()
print("A^+ A A^+:")
print_matrix(Check4_2)

Проверка 1.
(A A^+)^T:
0.500000		0.500000		0.000000		
0.500000		0.500000		0.000000		
0.000000		0.000000		1.000000		

A A^+:
0.500000		0.500000		0.000000		
0.500000		0.500000		0.000000		
0.000000		0.000000		1.000000		


Проверка 2.
(A^+ A)^T:
0.282913		0.044818		0.448179		
0.044818		0.997199		-0.028011		
0.448179		-0.028011		0.719888		

A^+ A:
0.282913		0.044818		0.448179		
0.044818		0.997199		-0.028011		
0.448179		-0.028011		0.719888		


Проверка 3.
A A^+ A:
-1.000000		4.000000		-2.000000		
-1.000000		4.000000		-2.000000		
1.000000		26.000000		-1.000000		
A:
-1.000000		4.000000		-2.000000		
-1.000000		4.000000		-2.000000		
1.000000		26.000000		-1.000000		


Проверка 4.
A^+ A A^+:
-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		

A^+ A A^+:
-0.121849		-0.121849		0.039216		
-0.002801		-0.002801		0.039216		
-0.194678		-0.194678		0.058824		
